### ISSUE TITLE
location of group names

### ISSUE THREAD

**Issue by larsborn** [TheSignalMessenger/TheSignal#15]
where should group names be stored? At a special entry at the location of the group?

**Comment by Mehrtuerer** [comment]
Sounds good. To avoid confusion the group's name should be the same to any member of the group. So it should onbly be possible to change the name globally.

**Comment by larsborn** [comment]
and this should be possible for every member of the group. This would keep it simple.

**Comment by larsborn** [comment]
duplicate to #21
